<?php declare(strict_types=1);

namespace Scraper\ScraperJeuxVideo\Tests\Request;

use Scraper\ScraperJeuxVideo\Model\Images;
use Scraper\ScraperJeuxVideo\Request\JeuxVideoGameImagesRequest;
use Symfony\Contracts\HttpClient\ResponseInterface;

/**
 * @internal
 */
final class JeuxVideoGameImagesRequestTest extends AbtractRequestTest
{
    public function testJeuxVideoGameImagesRequest(): void
    {
        $client = $this->getClient('game_images.json');

        $request = new JeuxVideoGameImagesRequest('partner', 'hash');
        $request
            ->setId(1237618)
            ->setMachineId(22)
        ;

        $result = $client->send($request);

        $this->assertInstanceOf(Images::class, $result);
    }

    public function requestCallback(string $method, string $url, array $options): ResponseInterface
    {
        $this->assertEquals('GET', $method);
        $this->assertEquals('https://api.jeuxvideo.com/v4/games/1237618/22/images', $url);
        $this->assertIsArray($options);

        return parent::requestCallback($method, $url, $options); // TODO: Change the autogenerated stub
    }
}
