<?php declare(strict_types=1);

namespace Scraper\ScraperJeuxVideo\Tests\Request;

use Scraper\ScraperJeuxVideo\Model\Config;
use Scraper\ScraperJeuxVideo\Request\JeuxVideoConfigRequest;
use Symfony\Contracts\HttpClient\ResponseInterface;

/**
 * @internal
 */
final class JeuxVideoConfigRequestTest extends AbtractRequestTest
{
    public function testJeuxVideoConfigRequest(): void
    {
        $client = $this->getClient('config.json');

        $request = new JeuxVideoConfigRequest('partner', 'hash');

        $result = $client->send($request);

        $this->assertInstanceOf(Config::class, $result);
    }

    public function requestCallback(string $method, string $url, array $options): ResponseInterface
    {
        $this->assertEquals('GET', $method);
        $this->assertEquals('https://api.jeuxvideo.com/v4/general/config', $url);
        $this->assertIsArray($options);

        return parent::requestCallback($method, $url, $options); // TODO: Change the autogenerated stub
    }
}
