<?php declare(strict_types=1);

namespace Scraper\ScraperJeuxVideo\Tests\Request;

use Scraper\ScraperJeuxVideo\Model\GameDetails;
use Scraper\ScraperJeuxVideo\Request\JeuxVideoGameDetailsRequest;
use Symfony\Contracts\HttpClient\ResponseInterface;

/**
 * @internal
 */
final class JeuxVideoGameDetailsRequestTest extends AbtractRequestTest
{
    public function testJeuxVideoGameDetailsRequest(): void
    {
        $client = $this->getClient('game_details.json');

        $request = new JeuxVideoGameDetailsRequest('partner', 'hash');
        $request
            ->setId(1237618)
            ->setMachineId(22)
        ;

        $result = $client->send($request);

        $this->assertInstanceOf(GameDetails::class, $result);
    }

    public function requestCallback(string $method, string $url, array $options): ResponseInterface
    {
        $this->assertEquals('GET', $method);
        $this->assertEquals('https://api.jeuxvideo.com/v4/games/1237618/22/details', $url);
        $this->assertIsArray($options);

        return parent::requestCallback($method, $url, $options); // TODO: Change the autogenerated stub
    }
}
